version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: pizza
      POSTGRES_PASSWORD: pizzaplanet
      POSTGRES_DB: pizzaplanet
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin: